image: node:18.18.0

stages:
  - build
  - deploy

build-pages:
  stage: build
  script:
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  
pages:
  stage: deploy
  script:
    - ls
  artifacts:
    paths:
      - public